- name: SimbirSoft_test_task_deploy_ubuntu_1804
  gather_facts: true
  hosts: all
  serial: 10
  remote_user: root
                    #For host OS Ubuntu 18.04
  tasks: 
     - name: Install the OS packages
       ansible.builtin.apt:
         name:
           - git
           - python3
           - python3-pip
         state: present
         update_cache: yes

     - name: Clone git repository
       ansible.builtin.git:
         repo: https://github.com/anfederico/Flaskex
         dest: /home/user/Flaskex
         version: main
         update: false

     - name: Install Python packages for UUID project
       ansible.builtin.pip:
         requirements: /home/user/Flaskex/requirements.txt
         state: present
         executable: pip3
         
     - name: add iptables rule
       ansible.builtin.iptables:
         chain: INPUT
         protocol: tcp
         destination_port: '8008'
         jump: ACCEPT         

     - name: Start Flaskex
       ansible.builtin.systemd:
         state: started
         enabled: yes
         daemon_reload: yes
         name: Flaseks
